CREATE ROLE admin NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD 'role_admin_pPassW0';
CREATE ROLE application NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD 'pPassW0';
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

CREATE USER liquibase_database_admin WITH PASSWORD 'Adm1nP@ss';
GRANT ALL PRIVILEGES ON DATABASE demo_cache_database to liquibase_database_admin;
GRANT CREATE ON SCHEMA public to liquibase_database_admin;
ALTER USER liquibase_database_admin CREATEROLE;